import { describe, expect, it } from "vitest";

import { backupCodeSchema } from "@/schemas/auth-schemas";

describe("backupCodeSchema", () => {
	it("accepts the backup-code format generated by Better Auth", () => {
		expect(backupCodeSchema.safeParse({ code: "Ab12C-xyZ89" }).success).toBe(
			true,
		);
	});

	it("trims a valid backup code", () => {
		expect(backupCodeSchema.parse({ code: "  Ab12C-xyZ89  " })).toEqual({
			code: "Ab12C-xyZ89",
		});
	});

	it("rejects malformed backup codes", () => {
		expect(backupCodeSchema.safeParse({ code: "123456" }).success).toBe(false);
	});
});
